"use strict";
var username = 'Haider Ali';
var roll = 22889;
var age = 21;
var auth = roll != null || age == null;
console.log('Your result is ', auth);
var auth = roll != null || age <= 45;
console.log('Your result is ', auth);
var auth = roll == 22889 || age > 23;
console.log('Your result is ', auth);
var auth = roll == null || age > 23;
console.log('Your result is ', auth);
console.log(" 'You are fire', 'Not' ");
console.log(` 'You are fire', "Yes" `);
